FROM public.ecr.aws/lambda/nodejs:22 AS build
RUN npm install --global pnpm@11.20.0
WORKDIR ${LAMBDA_TASK_ROOT}
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile
COPY nest-cli.json tsconfig.json tsconfig.build.json schema.graphql ./
COPY src ./src
RUN pnpm build

FROM public.ecr.aws/lambda/nodejs:22
WORKDIR ${LAMBDA_TASK_ROOT}
COPY --from=build ${LAMBDA_TASK_ROOT}/node_modules ./node_modules
COPY --from=build ${LAMBDA_TASK_ROOT}/dist ./dist
COPY package.json ./
CMD ["dist/src/image-processor.handler"]
